variables:
  GIT_SUBMODULE_STRATEGY: recursive

lassen-build:
    tags:
      - lassen
    script:
      - module load cuda/11
      - module load gcc/8
      - module load cmake/3.21
      - export CUDAFLAGS="--gpu-architecture sm_70"
      - mkdir build
      - cd build
      - ../configure --prefix=`pwd`../install --disable-debug
      - make -j8
      - make install
      - INQ_EXEC_ENV='jsrun -n 1 -M "-gpu"' bsub -nnodes 1 -q pbatch -I ctest -j 64 --output-on-failure
